ClubManager/Models/Clubs/ClubEvent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClubManager.Models.ClubModels
{
    [Table("ClubEvent")]
    public class ClubEvent
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Event ID")]
        public int EventId { get; set; }

        public string Venue { get; set; }

        public string Location { get; set; }

        [Display(Name = "Start Date Time")]
        //[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy @ hh:mm}")]
        public DateTime? StartDateTime { get; set; }

        [Display(Name = "End Date Time")]
        //[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy @ hh:mm}")]
        public DateTime? EndDateTime { get; set; }

        [ForeignKey("associatedClub")]
        public int ClubId { get; set; }

        public virtual Club associatedClub { get; set; }

        public virtual ICollection<Member> attendees { get; set; }

    }
}

ClubManager/Controllers/ClubEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClubManager.Models.ClubModels;
using ClubManager.Models.Clubs;
using System.Threading.Tasks;
using ClubManager.Models;

namespace ClubManager.Controllers
{
    public class ClubEventsController : Controller
    {
        private ClubDbContext db = new ClubDbContext();

        public PartialViewResult _Create(int? id)
        {
            if (id == null)
                throw new ArgumentNullException();
            else
                id = (int)id;

            return PartialView(new ClubEvent
            {
                ClubId = (int)id,
                StartDateTime = DateTime.Now,
                EndDateTime = DateTime.Now
            });
        }

        public async Task<ActionResult> Join(int? id)
        {
            if (id == null)
                throw new ArgumentNullException();
            else
                id = (int)id;

            using (ApplicationDbContext ctx = new ApplicationDbContext())
            {
                var user = ctx.Users.Where(u => u.Email == User.Identity.Name).First();

                var member = db.Members.Where(m => m.student.StudentId == user.StudentId).First();
                var ev = db.ClubEvents.Where(e => e.EventId == id).First();
                ev.attendees.Add(member);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Clubs", new { id = ev.ClubId});
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> _Create([Bind(Include = "EventID,Venue,Location,ClubId,StartDateTime,EndDateTime")] ClubEvent clubEvent)
        {
            if (ModelState.IsValid)
            {
                db.ClubEvents.Add(new ClubEvent
                {
                    ClubId = clubEvent.ClubId,
                    Venue = clubEvent.Venue,
                    Location = clubEvent.Location,
                    StartDateTime = clubEvent.StartDateTime,
                    EndDateTime = clubEvent.EndDateTime
                });
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Details", "Clubs", new { id = clubEvent.ClubId });
        }

        // GET: ClubEvents
        public ActionResult Index()
        {
            var clubEvents = db.ClubEvents.Include(c => c.associatedClub);
            return View(clubEvents.ToList());
        }

        public PartialViewResult _Attendees(int? id)
        {
            var data = db.ClubEvents
                .Where(ce => ce.EventId == id)
                .Select(m => m.attendees).First();
            return PartialView(data);
        }

        public PartialViewResult _ClubEvents(int? id)
        {
            ViewBag.clubId = id;
            var data = db.ClubEvents.Where(x => x.ClubId == id);
            return PartialView(data.ToList());
        }

        // GET: ClubEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubEvent clubEvent = db.ClubEvents.Find(id);
            if (clubEvent == null)
            {
                return HttpNotFound();
            }
            return View(clubEvent);
        }

        // GET: ClubEvents/Create
        public ActionResult Create()
        {
            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName");
            return View();
        }

        // POST: ClubEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,Venue,Location,StartDateTime,EndDateTime,ClubId")] ClubEvent clubEvent)
        {
            if (ModelState.IsValid)
            {
                db.ClubEvents.Add(clubEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName", clubEvent.ClubId);
            return View(clubEvent);
        }

        // GET: ClubEvents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubEvent clubEvent = db.ClubEvents.Find(id);
            if (clubEvent == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName", clubEvent.ClubId);
            return View(clubEvent);
        }

        // POST: ClubEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,Venue,Location,StartDateTime,EndDateTime,ClubId")] ClubEvent clubEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clubEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Clubs", new { id = clubEvent.ClubId });
            }
            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName", clubEvent.ClubId);
            return View(clubEvent);
        }

        // GET: ClubEvents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubEvent clubEvent = db.ClubEvents.Find(id);
            if (clubEvent == null)
            {
                return HttpNotFound();
            }
            return View(clubEvent);
        }

        // POST: ClubEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ClubEvent clubEvent = db.ClubEvents.Find(id);
            db.ClubEvents.Remove(clubEvent);
            db.SaveChanges();
            return RedirectToAction("Details", "Clubs", new { id = clubEvent.ClubId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClubManager/Views/ClubEvents/Create.cshtml
@model ClubManager.Models.ClubModels.ClubEvent

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClubEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Venue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Venue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Venue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubId, "ClubId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClubId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClubManager/Views/ClubEvents/Delete.cshtml
@model ClubManager.Models.ClubModels.ClubEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClubEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.associatedClub.ClubName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.associatedClub.ClubName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", "Clubs", new { id = Model.ClubId}, null)
        </div>
    }
</div>

ClubManager/Views/ClubEvents/Details.cshtml
@model ClubManager.Models.ClubModels.ClubEvent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>


<div>
    <h4>ClubEvent</h4>
    <div class="panel panel-default">
        <div class="panel-heading">@Html.DisplayFor(model => model.associatedClub.ClubName)</div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.StartDateTime)</dt>
                <dd>@Html.DisplayFor(model => model.StartDateTime)</dd>

                <dt>@Html.DisplayNameFor(model => model.EndDateTime)</dt>
                <dd>@Html.DisplayFor(model => model.EndDateTime)</dd>

                <dt>@Html.DisplayNameFor(model => model.Location)</dt>
                <dd>@Html.DisplayFor(model => model.Location)</dd>

                <dt>@Html.DisplayNameFor(model => model.Venue)</dt>
                <dd>@Html.DisplayFor(model => model.Venue)</dd>
            </dl>
        </div>
    </div>
    <hr />
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventId }) |
    @Html.ActionLink("Back to List", "Details", "Clubs", new {id = Model.ClubId }, null)
</p>

<div>
    @Html.Action("_Attendees", "ClubEvents", new { id = Model.EventId })
</div>

ClubManager/Views/ClubEvents/Edit.cshtml
@model ClubManager.Models.ClubModels.ClubEvent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClubEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)

        <div class="form-group">
            @Html.LabelFor(model => model.Venue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Venue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Venue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubId, "ClubId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClubId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details", "Clubs", new { id = Model.ClubId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClubManager/Views/ClubEvents/Index.cshtml
@model IEnumerable<ClubManager.Models.ClubModels.ClubEvent>

@{
    ViewBag.Title = "Index";
}

<h2>Club Event Index</h2>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.associatedClub.ClubName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Venue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </th>
        <th>
            <p>
                @Html.ActionLink("Create New", "Create")
            </p>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.associatedClub.ClubName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Venue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDateTime)
        </td>
        <td class="pad-anchors">
            @Html.ActionLink("Details", "Details", new { id = item.EventId })

            <a href="@Url.Action("Edit", "ClubEvents", new { id = item.EventId })" class="text-success">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>

            <a href="@Url.Action("Delete", "ClubEvents", new { id = item.EventId })" class="text-danger">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </td>
    </tr>
}

</table>

ClubManager/Views/ClubEvents/_Attendees.cshtml
@model IEnumerable<ClubManager.Models.ClubModels.Member>


<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.club.ClubName)</th>
        <th>@Html.DisplayNameFor(model => model.student.FirstName)</th>
        <th>@Html.DisplayNameFor(model => model.student.LastName)</th>
        <th>@Html.DisplayNameFor(model => model.Approved)</th>
        <th>

        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.club.ClubName)</td>
        <td>@Html.DisplayFor(modelItem => item.student.FirstName)</td>
        <td>@Html.DisplayFor(modelItem => item.student.LastName)</td>
        <td>@Html.DisplayFor(modelItem => item.Approved)</td>
        <td class="pad-anchors">
            @Html.ActionLink("Details", "Details", new { id = item.MemberId })

            <a href="@Url.Action("Edit", "ClubEvents", new { id = item.MemberId })" class="text-success">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>

            <a href="@Url.Action("Delete", "ClubEvents", new { id = item.MemberId })" class="text-danger">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </td>
    </tr>
}

</table>

ClubManager/Views/ClubEvents/_ClubEvents.cshtml
@model IEnumerable<ClubManager.Models.ClubModels.ClubEvent>


<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Venue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </th>
        <th>
            <p>
                @Html.ActionLink("Add", "_Create", "ClubEvents", new { id = (int?)ViewBag.clubId }, new { data_modal = "", @class = "btn btn-primary btn-sm" })
            </p>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Venue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDateTime)
            </td>
            <td class="pad-anchors">
                @Html.ActionLink("Details", "Details", new { id = item.EventId })

                @if (User.Identity.IsAuthenticated)
                {
                    <a href="@Url.Action("Join", "ClubEvents", new { id = item.EventId })" class="text-success">
                        <span class="glyphicon glyphicon-heart"></span>
                    </a>

                    if (User.IsInRole("Admin") || User.IsInRole("ClubAdmin"))
                    {
                        <a href="@Url.Action("Edit", "ClubEvents", new { id = item.EventId })" class="text-success">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    }

                    if (User.IsInRole("Admin"))
                    {
                        <a href="@Url.Action("Delete", "ClubEvents", new { id = item.EventId })" class="text-danger">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    }
                }

            </td>
        </tr>
    }

</table>

ClubManager/Views/ClubEvents/_Create.cshtml
@model ClubManager.Models.ClubModels.ClubEvent


@using (Html.BeginForm("_Create", "ClubEvents", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()

    <div class="modal-header">
        <a class="close" data-dismiss="modal" aria-hidden="True"> &times; </a>
        <h4 class="modal-title">Add New Club Event</h4>
    </div>

    <div class="modal-body">
        <input type="hidden" id="HiddenText" name="ClubId" value="@Model.ClubId" />
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Venue, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Venue, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Venue, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Cancel</a>
        <input class="btn btn-primary" type="submit" value="Add" />
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}